name: shared_package
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.10.4 <4.0.0'
  flutter: ">=3.38.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: 2.5.4
  hooks_riverpod: 3.1.0
  flutter_hooks: 0.21.3+1
  fpdart: 1.2.0
  riverpod_annotation: ^4.0.0
  freezed_annotation: 3.1.0
  json_annotation: 4.9.0
  firebase_core: 4.3.0
  firebase_auth: 6.1.3
  firebase_database: 12.1.1
  firebase_storage: 13.0.5
  google_sign_in: 7.2.0
  grpc: 5.1.0
  protobuf: 6.0.0
  fixnum: 1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  freezed: 3.2.3
  json_serializable: 6.11.2
  build_runner: 2.10.4
  riverpod_generator: 4.0.0+1
  mocktail: ^1.0.4

flutter:
